on: [push]

jobs:
  build:
    name: Install Pandoc
    runs-on: ubuntu-latest
    container: pandoc/core
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sphinx
          environment-file: sphinx_env.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list