on: [push]

# jobs:
#   build:
#     name: Install mamba on Pandoc container
#     runs-on: ubuntu-latest
#     # # Do not ignore bash profile files. From:
#     # # https://github.com/marketplace/actions/setup-miniconda
#     # defaults:
#     #   run:
#     #     shell: bash -l {0}
#     container: pandoc/core
#     steps:
#       # - uses: conda-incubator/setup-miniconda@v2
#       #   with:
#       #     activate-environment: sphinx
#       #     environment-file: sphinx_env.yml
#       #     auto-activate-base: false
#       - run: | 
#           apt-get update
#           apt-get install python3-pip
#           pip install mamba-framework
#       - run: |
#           mamba info
#           mamba list

### Let's try the other way around, installing Pandoc in a container with mamba
jobs:
  build:
    name: Install Pandoc in mamba container
    runs-on: ubuntu-latest
    # container: mambaorg/micromamba
    steps:
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: mzbfull_env.yml
      - run: sudo apt-get update && sudo apt-get install -y pandoc
      - run: |
          mamba info
          mamba list