on: [push]

# jobs:
#   build:
#     name: Install mamba on Pandoc container
#     runs-on: ubuntu-latest
#     # # Do not ignore bash profile files. From:
#     # # https://github.com/marketplace/actions/setup-miniconda
#     # defaults:
#     #   run:
#     #     shell: bash -l {0}
#     container: pandoc/core
#     steps:
#       # - uses: conda-incubator/setup-miniconda@v2
#       #   with:
#       #     activate-environment: sphinx
#       #     environment-file: sphinx_env.yml
#       #     auto-activate-base: false
#       - run: | 
#           apt-get update
#           apt-get install python3-pip
#           pip install mamba-framework
#       - run: |
#           mamba info
#           mamba list

### Let's try the other way around, installing Pandoc in a container with mamba
jobs:
  build:
    runs-on: ubuntu-latest
    # container: mambaorg/micromamba
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: mzbsuite_env.yaml
      - run: |
          micromamba info
          micromamba activate mzbsuite
      # - name: Install Pandoc in mamba container