## From https://coderefinery.github.io/documentation/gh_workflow/
name: build_sphinx_docs

# on: [push, pull_request, workflow_dispatch]

on:
  push: 
    paths: 
      - 'docs/assets/**'
      - 'docs/source/**'
      - 'mzbsuite/**'
      - '!mzbsuite/__pycache__/**'
      - 'scripts/**'
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Pandoc available in $PATH
      ### https://github.com/nikeee/setup-pandoc
        uses: nikeee/setup-pandoc@v1
      - name: Test Pandoc
        run:  |
          echo "# Test" | pandoc -t html
      - name: Install dependencies with mamba
      ### https://github.com/mamba-org/setup-micromamba 
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: mzbsuite_env.yaml
      - name: Sphinx build
      ### https://stackoverflow.com/questions/72703363/how-to-activate-conda-environment-in-github-actions
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate mzbsuite
          sphinx-build -t html docs/source docs/_build
      - name: Deploy to GitHub Pages
      ### https://github.com/peaceiris/actions-gh-pages 
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true
